name: Generate Snake Game 🐍

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours à minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Zenbx
          outputs: dist
      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
